name: Deploy to Private Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build app
        run: make build

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: 10.255.38.26:142
          username: root
          password: M!w6By7#6%
          source: ./
          target: /root/mtek-api/attendance

      - name: Restart app with PM2
        run: pm2 restart attendance
